[package]
name = "tuix"
description = "Cross-platform GUI toolkit"
version = "0.1.0"
authors = ["George Atkinson"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["ui", "gui", "gpu", "graphics", "css"]
repository = "https://github.com/geom3trik/tuix"
edition = "2018"

[workspace]
members = [
    "glutin",
    "baseview",
    "core",
]

[features]
default = ["glutin"]
glutin = ["tuix_glutin"]
baseview = ["tuix_baseview"]

[dependencies]
tuix_core = { version = "0.1.0", path = "core" }
tuix_glutin = { version = "0.1.0", path = "glutin", optional = true }
tuix_baseview = { version = "0.1.0", path = "baseview", optional = true }

[dev-dependencies]
femtovg = { git = "https://github.com/femtovg/femtovg", branch = "master", default-features = false }
image = "0.23.12"